config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/update', :to => 'users#updateFollows'

  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy'

  get '/auth', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#new'

  get '/auth/twitter/callback', :to => 'users#addTwitter'

  get '/games/search/name', :to => 'games#search_for_name', :as => 'search_game_names'
  get '/search', :to => 'users#search', :as => 'search'

  resources :users do
    resources :streams
    resources :weekly_streams
  end

  resources :games

end

app/models/weekly_stream.rb
class WeeklyStream < ActiveRecord::Base

  belongs_to :user

  def weeklyCreate
    @stream = Stream.new
    @stream.user = self.user
    @stream.title = self.title
    @stream.description = self.description
    @stream.game = self.game
    @stream.tweet = self.tweet
    @stream.starttime = Chronic.parse('next ' + self.day + ' ' + self.starttime.to_s(:time))
    @stream.endtime = Chronic.parse('next ' + self.day + ' ' + self.endtime.to_s(:time))
    @stream.save!
  end

end

app/controllers/weekly_streams_controller.rb
class WeeklyStreamsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @stream = WeeklyStream.new
  end

  def create
    @user = User.find(params[:user_id])
    if params.has_key?(:weekly_stream)
      @stream = @user.weekly_streams.create(weekly_stream_params)

      @game = Game.find_by_id(@stream.game.to_i)
      @stream.game = @game.name
      @stream.save!

      @stream.weeklyCreate

      redirect_to user_weekly_stream_path(@user, @stream)
    else
      render 'new'
    end
  end

  def show
    @stream = WeeklyStream.find(params[:id])
    @user = User.find(@stream.user_id)
  end

  def edit
    @stream = WeeklyStream.find(params[:id])
    @user = User.find(@stream.user_id)
  end

  def update
    @stream = WeeklyStream.find(params[:id])
    @user = User.find(@stream.user_id)

    @stream.update(stream_params)
    redirect_to user_stream_path(@user, @stream)
  end

  def destroy
    @stream = WeeklyStream.find(params[:id])
    @user = User.find(@stream.user_id)
    @stream.destroy

    redirect_to url_for(@user)
  end


  private
  def weekly_stream_params
    params.require(:weekly_stream).permit(:description, :title, :game, :starttime, :endtime, :day, :tweet)
  end


end

app/helpers/weekly_streams_helper.rb
module WeeklyStreamsHelper
end

app/views/weekly_streams/edit.html.erb
<h3>Edit Scheduled Stream</h3>

<%= form_for :stream, url: user_stream_path(@user, @stream), method: :patch do |f| %>


<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :game %><br>
  <%= f.text_field :game %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label "Start time" %><br>
  <%= f.datetime_select :starttime %>
</p>

<p>
  <%= f.label "End time" %><br>
  <%= f.datetime_select :endtime %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>
<%= link_to 'Back', url_for(@user) %>

app/views/weekly_streams/new.html.erb
<h3>New Scheduled Weekly Stream</h3>

<%= form_for ([@user, @user.weekly_streams.build]) do |f| %>


<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :game %><br>
  <%= f.hidden_field :game, class: 'select2 ajax', style: 'width: 20%',
      data: { source: search_game_names_path, placeholder: 'Search for a game' } %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :day %><br>
  <%= f.text_field :day %>
</p>

<p>
  <%= f.label "Start time" %><br>
  <%= f.time_select :starttime %>
</p>

<p>
  <%= f.label "End time" %><br>
  <%= f.time_select :endtime %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>
<%= link_to 'Back', url_for(@user) %>

app/views/weekly_streams/show.html.erb
<h3><%= @stream.title %></h3>

<p>Streamer: <%= @user.name %></p>
<p>Game: <%= @stream.game %></p>
<p>Day: <%= @stream.day %></p>
<p>Start time: <%= @stream.starttime.to_s(:time) %></p>
<p>End time: <%= @stream.endtime.to_s(:time) %></p>
<p>Description: <%= @stream.description %></p>
<p>Tweet: <%= @stream.tweet %></p>

<% if @user.name == session[:name] %>
<%= link_to "Edit stream", edit_user_weekly_stream_path(@user, @stream) %> |
<%= link_to "Delete stream", [@user, @stream], :method => :delete %>
<% end %>
<br>

<%= link_to "Back", user_path(@user) %>