config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/update', :to => 'users#updateFollows'

  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy'

  get '/auth', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#new'

  get '/auth/twitter/callback', :to => 'users#addTwitter'

  get '/games/search/name', :to => 'games#search_for_name', :as => 'search_game_names'
  get '/search', :to => 'users#search', :as => 'search'

  resources :users do
    resources :streams
    resources :weekly_streams
  end

  resources :games

end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :follows

  has_many :streams
  has_many :weekly_streams

  searchable do
    text :name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @user.name = session[:name]

    @twitch = Twitch.new({
      :access_token => session[:access_token]
    })

    @apifollowing = @twitch.getAllFollows(@user.name)
    @following = []
    @apifollowing[:body]["follows"].each do |channel|
      if User.find_by_name(channel["channel"]["display_name"])
        @following.push(channel["channel"]["display_name"])
      end
    end

    @user.follows = @following

    @user.save
    redirect_to action: 'index'
  end

  def index
    @user = User.find_by_name(session[:name])

    if @user
      @twitch = Twitch.new({
        :access_token => session[:access_token]
      })

      @liveStreams = @twitch.getYourFollowedStreams()[:body]["streams"]

      @scheduledStreams = []

      @user.follows.each do |streamer|
        @dbstreamer = User.find_by_name(streamer)
        @scheduledStreams.concat(@dbstreamer.streams.all)
      end

      @scheduledStreams.sort_by! {|obj| obj.starttime}

    else
      @twitch = Twitch.new({})

      @liveStreams = @twitch.getStreams()[:body]["streams"]
    end
  end

  def show
    @user = User.find(params[:id])
    @streams = Array(@user.streams.all)
    @streams.sort_by! {|obj| obj.starttime}

    @weeklyStreams = Array(@user.weekly_streams.all)

    @twitch = Twitch.new
    @tuser = @twitch.getUser(@user.name)
    @logo = @tuser[:body]["logo"]
    @description = @tuser[:body]["bio"]

    @following = @twitch.getAllFollows(@user.name)[:body]["follows"]
    @followers = @twitch.getAllFollowing(@user.name)[:body]["follows"]

    puts(@following, @followers)

    @userStream = @twitch.getStream(@user.name)[:body]

  end

  def updateFollows
    @user = User.find_by_name(session[:name])

    @twitch = Twitch.new({
      :access_token => session[:access_token]
    })

    @apifollowing = @twitch.getAllFollows(@user.name)
    @following = []
    @apifollowing[:body]["follows"].each do |channel|
      if User.find_by_name(channel["channel"]["display_name"])
        @following.push(channel["channel"]["display_name"])
      end
    end

    @user.follows = @following

    @user.save
    redirect_to action: 'index'
  end

  def search
    @searchUsers = User.search do
      fulltext params[:search]
    end
    @users = @searchUsers.results

    @searchGames = Game.search do
      fulltext params[:search]
    end
    @games = @searchGames.results

    @searchStreams = Stream.search do
      fulltext params[:search]
    end
    @streams = @searchStreams.results
  end

  def addTwitter
    @user = User.find_by_name(session[:name])
    auth = request.env["omniauth.auth"]

    @user.token = auth[:credentials][:token]
    @user.secret = auth[:credentials][:secret]

    @user.save!

    redirect_to user_path(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<center>

    <div class="jumbotron">
<div class='container' id='TopStreams'>
  <p style="text-decoration: underline">Streams Live Now</p>
  <table class='table table-bordered' id='TopStreamsTable'>

    <tr>
      <th>Streamer</th>
      <th>Game</th>
      <th>Viewers</th>
    </tr>

    <% @liveStreams.each do |stream| %>
    <tr>
      <% @suser = User.find_by_name(stream["channel"]["display_name"]) %>
      <% if @suser %>
      <td><a href=" <%= user_path(@suser) %>"><%= @suser.name %></a></td>
      <% else %>
      <td><a href=" <%= stream['channel']['url'] %> " target="_blank"> <%= stream["channel"]["display_name"] %></a></td>
      <% end %>
      <td><%= stream["game"] %> </td>
      <td><%= stream["viewers"] %> </td>
    </tr>
    <% end %>
  </table>
</div>
</div>
<% if @scheduledStreams %>
<div class="jumbotron">
<div class='container' id='NextStreams'>
  <p style="text-decoration: underline">Upcoming streams</p>
  <table class='table table-bordered' id='NextStreamsTable'>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Streamer</th>
      <th>Title</th>
      <th>Game</th>
      <th>Full description</th>
    </tr>

    <% @scheduledStreams.each do |stream| %>
    <tr>
      <td><%= stream.starttime.strftime("%b %d, %I:%M %p") %></td>
      <td><%= stream.endtime.strftime("%b %d, %I:%M %p") %></td>
      <td><a href=" <%= user_path(stream.user) %>"><%= stream.user.name %></a></td>
      <td><%= stream.title %></td>
      <td><%= stream.game %></td>
      <td><%= link_to "More...", user_stream_path(stream.user, stream) %></td>
    </tr>
    <% end %>
  </table>
</div>
</div>
<% end %>
</center>

app/views/users/search.html.erb
<% if @users != [] %>
<h3>Users</h3>
<table>
<% @users.each do |user| %>
<tr><td><a href=" <%= user_path(user) %>"><%= user.name %></a></td></tr>
<% end %>
</table>
<% end %>

<% if @games != [] %>
<h3>Games</h3>
<table>
<% @games.each do |game| %>
<tr><td><a href=" <%= game_path(game) %>"><%= game.name %></a></td></tr>
<% end %>
</table>
<% end %>

<% if @streams != [] %>
<h3>Streams</h3>
<table>
<% @streams.each do |stream| %>
<tr><td><a href=" <%= user_stream_path(stream.user, stream) %>"><%= stream.title %></a></td></tr>
<% end %>
</table>
<% end %>

app/views/users/show.html.erb
<center>
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="<%= @logo %>" alt="Profile picture" height=60 width=60>
    </a>
  </div>
  <div class="media-body">
      <h2 class="media-heading" onclick="location.href='http://www.twitch.tv/<%= @user.name %>'"><%= @user.name %></h2>
    <p><%= @description %></p>
  </div>
    <br >
</div>


<% if @userStream["stream"]%>
  <iframe height="378" width="620" frameborder="0" scrolling="no" src="http://www.twitch.tv/<%= @user.name %>/embed"></iframe>
<% end %>
</center>
<script type="text/javascript">
    var frames;

    $(document).ready(function () {
        frames = ["List", "Calendar", "Following", "Followers", "Settings"];
        for(j = 0; j < frames.length; j++){
            $("#"+frames[j]).hide();
        }
        $("#"+frames[0]).show();
    });

    function swapFrame(butan,frm) {
        for(j = 0; j < frames.length; j++){
            $("#"+frames[j]).hide();
            $("#b"+j).attr("class", "btn btn-primary inactive");
        }
        for(i = 0; i < frames.length; i++){
            if(i == frm){
                $("#"+frames[i]).show();
                $("#b"+i).attr("class", "btn btn-primary active");
            }
        }
    }
</script>

<script type="text/javascript">
    var frames;

    $(document).ready(function () {
        frames = ["List", "Calendar", "Following", "Followers", "Settings"];
        for(j = 0; j < frames.length; j++){
            $("#"+frames[j]).hide();
        }
        $("#"+frames[0]).show();
    });

    function swapFrame(butan,frm) {
        for(j = 0; j < frames.length; j++){
            $("#"+frames[j]).hide();
            $("#b"+j).attr("class", "btn btn-primary inactive");
        }
        for(i = 0; i < frames.length; i++){
            if(i == frm){
                $("#"+frames[i]).show();
                $("#b"+i).attr("class", "btn btn-primary active");
            }
        }
    }
</script>

<div class='jumbotron'>
    <div class="container-fluid">
    <div class="col-md-1" id='midJumbo'>
        <br>
        <br>
        <div class="btn-group-vertical" width="100%" role="group">
            <button id="b0" class="btn btn-primary active" onclick="swapFrame(this, 0)">List</button>
            <button id="b1" class="btn btn-primary inactive" onclick="swapFrame(this, 1)">Calendar</button>
            <button id="b2" class="btn btn-primary inactive" onclick="swapFrame(this, 2)">Following</button>
            <button id="b3" class="btn btn-primary inactive" onclick="swapFrame(this, 3)">Followers</button>
            <button id="b4" class="btn btn-primary inactive" onclick="swapFrame(this, 4)">Settings</button>
        </div>
    </div>
        <div class="col-md-1" id='midJumbo'></div>
        <center>
    <div class="col-md-8" id='midJumbo'>

        <div id="List">
<div id='UserStreams'>
  <p style="text-decoration: underline">Scheduled Streams</p>


  <table class='table table-bordered' id='UserStreamsTable'>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Title</th>
      <th>Game</th>
      <th>Description</th>
    </tr>

    <% @streams.each do |stream| %>

    <tr>
      <td><%= stream.starttime.strftime("%b %d, %I:%M %p") %></td>
      <td><%= stream.endtime.strftime("%b %d, %I:%M %p") %></td>
      <td><%= stream.title %></td>
      <td><%= stream.game %></td>
      <td><%= link_to "More...", user_stream_path(stream.user, stream) %></td>
    </tr>
    <% end %>
  </table>

  <p style="text-decoration: underline">Weekly Scheduled Streams</p>

  <table class='table table-bordered' id='UserStreamsTable'>
    <tr>
      <th>Day</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Title</th>
      <th>Game</th>
      <th>Description</th>
    </tr>

    <% @weeklyStreams.each do |stream| %>

    <tr>
      <td><%= stream.day %> </td>
      <td><%= stream.starttime.to_s(:time) %></td>
      <td><%= stream.endtime.to_s(:time) %></td>
      <td><%= stream.title %></td>
      <td><%= stream.game %></td>
      <td><%= link_to "More...", user_weekly_stream_path(stream.user, stream) %></td>
    </tr>
    <% end %>
  </table>
</div>
    </div>

        <div id="Calendar">
            <p style="text-decoration: underline">Scheduled Streams</p>
        </div>

        <div id="Following">
            <p style="text-decoration: underline">Following</p>
              <table class='table table-striped' id='UserStreamsTable'>
                <tr>
                  <th>Icon</th>
                  <th>User</th>
                </tr>
                <% @following.each do |follow| %>
                <tr>
                  <td><img src="<%= follow["channel"]["logo"] %>" height=40 width=40 ></td>
                  <td><%= follow["channel"]["name"] %></td>
                </tr>
                <% end %>

              </table>
        </div>

        <div id="Followers">
            <p style="text-decoration: underline">Followers</p>
            <table class='table table-striped' id='UserStreamsTable'>
                <tr>
                  <th>Icon</th>
                  <th>User</th>
                </tr>

                <% @followers.each do |follow| %>
                <tr>
                  <td><img src="<%= follow["user"]["logo"] %>" height=40 width=40 ></td>
                  <td><%= follow["user"]["name"] %></td>
                </tr>
                <% end %>
              </table>
        </div>


        <div id="Settings">
            <p style="text-decoration: underline">Settings</p>
        </div>

        </div>
            <div class="col-md-2" id='midJumbo'></div>
    </div>
</div>
    </center>