config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get '/update', :to => 'users#updateFollows'

  get '/login', :to => 'sessions#new', :as => :login
  get '/logout', :to => 'sessions#destroy'

  get '/auth', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#new'

  get '/auth/twitter/callback', :to => 'users#addTwitter'

  get '/games/search/name', :to => 'games#search_for_name', :as => 'search_game_names'
  get '/search', :to => 'users#search', :as => 'search'

  resources :users do
    resources :streams
    resources :weekly_streams
  end

  resources :games

end

app/models/game.rb
class Game < ActiveRecord::Base

  scope :finder, lambda { |q| where("name ILIKE :q", q: "%#{q}%") }

  searchable do
    text :name
  end

  def as_json(options)
    { id: id, text: name }
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    @game.save
  end

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @streams = Stream.where("game = ?", @game.name)
  end

  def search_for_name
    @games = Game.order('name').
    finder(params[:q]).page(params[:page]).per(params[:per])
    respond_to do |format|
      format.html
      format.json { render json: @games }
    end
  end

  private
  def game_params
    params.require(:game).permit(:name)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<table>

  <% @games.each do |game| %>
  <tr>
    <td><a href="<%= game_path(game) %>"> <%= game.name %> </a></td>
  </tr>
  <% end %>

</table>

app/views/games/show.html.erb
<h3><%= @game.name %></h3>

<div id='NextStreams'>
  <p style="text-decoration: underline">Upcoming streams</p>
  <table id='NextStreamsTable'>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Streamer</th>
      <th>Title</th>
      <th>Game</th>
      <th>Full description</th>
    </tr>

    <% @streams.each do |stream| %>
    <tr>
      <td><%= stream.starttime.strftime("%b %d, %I:%M %p") %></td>
      <td><%= stream.endtime.strftime("%b %d, %I:%M %p") %></td>
      <td><a href=" <%= user_path(stream.user) %>"><%= stream.user.name %></a></td>
      <td><%= stream.title %></td>
      <td><%= stream.game %></td>
      <td><%= link_to "More...", user_stream_path(stream.user, stream) %></td>
    </tr>
    <% end %>
  </table>
</div>